name: Convert ELAN to TEI
env:
  DOCKER_TAG: ghcr.io/acdh-oeaw/shawi-data/shawi-noske
on:
  push: {}
  repository_dispatch:
    types: [run]
  workflow_dispatch: {}
# ${{ secrets.ACDH_KUBE_CONFIG }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: convert ELAN to TEI
        env:
          SP_USERNAME: ${{ secrets.SP_USERNAME }}
          SP_PWD: ${{ secrets.SP_PWD }}
        run: |
          python --version
          # export PYENV_ROOT="$HOME/.pyenv"
          # export PATH="$PYENV_ROOT/bin:$PATH"
          # curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          # eval "$(pyenv init -)"
          # eval "$(pyenv virtualenv-init -)"
          # pyenv install 3.10.4
          pip install pipenv
          cd 080_scripts_generic/080_01_ELAN2TEI
          pipenv install
          pipenv run jupyter nbconvert --to script ELAN2TEI.ipynb
          pipenv run python ELAN2TEI.py
      - name: Commit auto generated files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 103_tei_w/*.xml
          git add 130_vert_plain/*.txt
          git commit -m "Automatic generated TEI files" -a
      - name: Push changes back to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to ghcr.io      
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./nosketchengine/Dockerfile
          tags: |
            ${{ env.DOCKER_TAG }}:${{ github.ref_name }}
          push: true
  _3:
    needs: [build]
    uses: acdh-oeaw/gl-autodevops-minimal-port/.github/workflows/deploy-aks.yml@main
    secrets: inherit
    with:
      DOCKER_TAG: ${{ env.DOCKER_TAG }}:${{ github.ref_name }}
      APP_NAME: "shawi-noske"
      APP_ROOT: "/"
      SERVICE_ID: "20740"
      PUBLIC_URL: "shawi-noske.acdh-dev.oeaw.ac.at"
      POSTGRES_ENABLED: false
      environment: "${{ github.ref_name }}"