name: Convert ELAN to TEI
# env: {}
on:
  push: {}
  repository_dispatch:
    types: [run]
# ${{ secrets.ACDH_KUBE_CONFIG }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: generate build instructions using herokuish
        run: |
          python --version
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          exec $SHELL
          export PATH="$HOME/.pyenv/bin:$PATH"
          pyenv install 3.10.4
          pip install pipenv
          cd 080_scripts_generic/080_01_ELAN2TEI
          pipenv install
          pipenv run python --version
